### ISSUE TITLE
You're new to open-source, here you can go🚀

### ISSUE THREAD

**Issue by GeekGiggle** [GeekGiggle/hacktoberfest#1]
Welcome to Hacktoberfest 2024! 🎉 If you're new to open-source or JavaScript, this is the perfect place to start!
What you can contribute:

- Add a simple JavaScript project to the repository. It could be a calculator, to-do list, or any beginner-friendly project. How to contribute:
- Create your project locally.
- Add it to a new folder within the JavaScript directory.
- Raise a pull request with a short description of your project. We're looking forward to seeing your amazing projects!

**Comment by parthib2004** [comment]
Can you please assign these to me?

**Comment by Sofiyan-coder** [comment]
Hi @GeekGiggle  , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by Balaji91221** [comment]
Hello, @GeekGiggle Would you kindly give me this problem? With this project, I would love to contribute and begin my open-source journey!

**Comment by SuchitraShankar07** [comment]
@GeekGiggle please assign this issue to me!

**Comment by sriram-pv** [comment]
hello, @GeekGiggle , Could you please assign the issue to me.
Thank you.

**Comment by utkarsh-2033** [comment]
@GeekGiggle  please assign.
