### ISSUE TITLE
Distinguish Colors in Simon Game

### ISSUE THREAD

**Issue by GeekGiggle** [GeekGiggle/hacktoberfest#23]
In the current Simon Game implementation, all the colors appear to be the same, making it difficult for users to differentiate between them. The task is to modify the CSS or JavaScript to apply distinct, vibrant colors for each section of the game (e.g., red, green, yellow, blue) to enhance visual clarity and gameplay experience.

**Comment by pranay-gedam** [comment]
Ok, I will make the changes.
