### ISSUE TITLE
Develop a Currency Converter web app

### ISSUE THREAD

**Issue by GeekGiggle** [GeekGiggle/hacktoberfest#4]
Build a project that converts one currency to another using exchange rates in **realtime conversion rates**. The program should prompt users to input the currency type and amount, and display the converted value.

**Comment by Abhishtt21** [comment]
Hii @GeekGiggle I am starting open-source and would like to work on this, can you assign this to me

**Comment by GeekGiggle** [comment]
> Hii @GeekGiggle I am starting open-source and would like to work on this, can you assign this to me

ya you can do this, just follow the instructions mentioned in the readme file

**Comment by Tiwari-Ankush** [comment]
Assign me this project please, i have best project

**Comment by HackesticMedusa** [comment]
I’d like to work on a project that converts one currency to another using real-time exchange rates. The program will prompt users to input the currency type and amount, and then display the converted value. This feature will enhance the usability of our application by providing up-to-date currency conversion information.

**Comment by ayush-py-c** [comment]
I hope you're doing well! I’d like to work on the issue Develop a Currency Converter web app #4 . Could you please assign it to me? I believe I can make meaningful progress
