### ISSUE TITLE
JavaScript Password Generator

### ISSUE THREAD

**Issue by Kimayaa1** [GeekGiggle/hacktoberfest#44]
Hey @GeekGiggle, I would like to add the code for random password generator using JavaScript.
Can you please assign this to me?

**Comment by Sofiyan-coder** [comment]
@GeekGiggle  hey assign me this issue I would like to work on it.

**Comment by SuchitraShankar07** [comment]
@GeekGiggle hey id like to work on this! pleae assign it to me
