### ISSUE TITLE
First Non-Code Contribution: Update "entry.html"

### ISSUE THREAD

**Issue by GeekGiggle** [GeekGiggle/hacktoberfest#5]
This issue is aimed at encouraging beginners to make their first non-code contribution to the Hacktoberfest repository by updating the **`entry.html`** file. Your task is to add your name to the contributors' list in the HTML file. This is a simple yet valuable way to start contributing to open source!

- **Steps to Complete the Contribution**:
  1. **Fork the Repository**: Click on the "Fork" button at the top right of the repository page to create a copy of the repository under your GitHub account.
  2. **Clone Your Fork**: Use the following command in your terminal to clone your forked repository to your local machine:
     ```bash
     git clone https://github.com/YOUR_USERNAME/YOUR_FORKED_REPOSITORY.git
     ```
     Replace `YOUR_USERNAME` and `YOUR_FORKED_REPOSITORY` with your GitHub username and the repository name, respectively.
  3. **Navigate to the Directory**: Change into the cloned repository's directory:
     ```bash
     cd YOUR_FORKED_REPOSITORY
     ```
  4. **Open `entry.html`**: Open the `entry.html` file in your preferred code editor.
  5. **Add Your Name**: Scroll to the "Contributors" section and append your name between the `<h4>...</h4>` tags. For example:
     ```html
     <h4>Your Name❤️</h4>
     ```
     Make sure to replace "Your Name" with your actual name.
  6. **Save Changes**: Save the file after making the changes.
  7. **Commit Your Changes**: In your terminal, run the following commands to stage and commit your changes:
     ```bash
     git add entry.html
     git commit -m "Added my name to the contributors list"
     ```
  8. **Push Your Changes**: Push your changes to your forked repository:
     ```bash
     git push origin main
     ```
  9. **Create a Pull Request**: Go to your forked repository on GitHub, and click on the "Compare & pull request" button to submit your changes for review.

**Comment by parthib2004** [comment]
Can you please assign this to me?

**Comment by Jash2606** [comment]
Hey @GeekGiggle , 
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by Swadeeppatil** [comment]
hello @GeekGiggle 
plz assign me this issue under hacktoberfest2024
